# Generated by Django 2.2.3 on 2019-09-09 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exx', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RobotManagement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curry', models.CharField(max_length=32)),
                ('market', models.CharField(max_length=32)),
                ('total_money', models.DecimalField(decimal_places=2, max_digits=19)),
                ('realized_profit', models.DecimalField(decimal_places=2, max_digits=19)),
                ('total_profit', models.DecimalField(decimal_places=2, max_digits=19)),
                ('pub_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.SmallIntegerField(choices=[('运行中', 1), ('已停止', 0)])),
                ('trading_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exx.Account')),
            ],
        ),
        migrations.DeleteModel(
            name='Girdding',
        ),
    ]
