# Generated by Django 2.2.4 on 2019-09-20 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rbac', '0004_auto_20190910_1037'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, unique=True, verbose_name='账户名称')),
                ('accesskey', models.CharField(max_length=128, unique=True)),
                ('secretkey', models.CharField(max_length=128, unique=True)),
                ('createtime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='TradingPlatform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Platform_name', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Robot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=32)),
                ('market', models.CharField(max_length=32)),
                ('trading_strategy', models.CharField(max_length=32)),
                ('total_money', models.DecimalField(decimal_places=2, max_digits=19)),
                ('float_profit', models.DecimalField(decimal_places=2, max_digits=19)),
                ('realized_profit', models.DecimalField(decimal_places=2, max_digits=19)),
                ('total_profit', models.DecimalField(decimal_places=2, max_digits=19)),
                ('annual_yield', models.DecimalField(decimal_places=2, max_digits=5)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.SmallIntegerField(choices=[('运行中', 1), ('已停止', 0)])),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('orders_frequency', models.IntegerField()),
                ('resistance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('support_level', models.DecimalField(decimal_places=2, max_digits=10)),
                ('girding_num', models.IntegerField()),
                ('procudere_fee', models.CharField(max_length=10)),
                ('min_num', models.IntegerField()),
                ('max_num', models.IntegerField()),
                ('girding_profit', models.CharField(max_length=32)),
                ('stop_price', models.DecimalField(decimal_places=2, max_digits=19)),
                ('warning_price', models.DecimalField(decimal_places=2, max_digits=19)),
                ('warning_account', models.CharField(max_length=32)),
                ('trading_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deal.Account')),
            ],
            options={
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=32)),
                ('original_assets', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('charge_record', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('withdraw_record', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('currency_status', models.CharField(default='0', max_length=10)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='deal.Account')),
            ],
        ),
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.CharField(max_length=10)),
                ('closing_price', models.DecimalField(decimal_places=8, max_digits=18)),
                ('total_price', models.DecimalField(decimal_places=8, max_digits=18)),
                ('closing_time', models.DateTimeField()),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='deal.Account')),
            ],
        ),
        migrations.CreateModel(
            name='LastdayAssets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=32)),
                ('lastday_assets', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('last', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='deal.Account')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='platform',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='deal.TradingPlatform'),
        ),
        migrations.AddField(
            model_name='account',
            name='users',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rbac.UserInfo'),
        ),
    ]
