# Generated by Django 2.2.4 on 2019-09-04 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rbac', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, unique=True)),
                ('accesskey', models.CharField(max_length=128, unique=True)),
                ('secretkey', models.CharField(max_length=128, unique=True)),
                ('createtime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TradingPlatform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Platform_name', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=32)),
                ('original_assets', models.DecimalField(decimal_places=2, max_digits=10)),
                ('charge_record', models.CharField(default='0', max_length=32)),
                ('withdraw_record', models.CharField(default='0', max_length=32)),
                ('lastday_assets', models.CharField(max_length=32)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='deal.Account')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='platform',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='deal.TradingPlatform'),
        ),
        migrations.AddField(
            model_name='account',
            name='users',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rbac.UserInfo'),
        ),
    ]
