# Generated by Django 2.2.4 on 2019-09-05 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='currency_status',
            field=models.CharField(default='0', max_length=10),
        ),
    ]
