# Generated by Django 2.2.3 on 2019-09-20 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderinfo',
            old_name='account',
            new_name='robot',
        ),
    ]
