# Generated by Django 2.2.3 on 2019-09-26 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0002_auto_20190920_1716'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['-createtime']},
        ),
        migrations.AddField(
            model_name='robot',
            name='protection',
            field=models.SmallIntegerField(choices=[('保护', 1), ('解除保护', 2)], default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='accesskey',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='account',
            name='secretkey',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='account',
            name='users',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='rbac.UserInfo'),
            preserve_default=False,
        ),
    ]
