# Generated by Django 2.2.4 on 2019-09-07 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0002_property_currency_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='charge_record',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='property',
            name='lastday_assets',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='property',
            name='original_assets',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='property',
            name='withdraw_record',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=18),
        ),
    ]
