# Generated by Django 2.2.3 on 2019-09-21 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0002_auto_20190920_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfo',
            name='currency_pair',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='order_id',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
    ]
