# Generated by Django 2.2.3 on 2019-10-11 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0002_auto_20191009_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robot',
            name='protection',
            field=models.SmallIntegerField(choices=[(1, '保护'), (0, '解除')], default=0),
        ),
        migrations.AlterField(
            model_name='robot',
            name='run_status',
            field=models.SmallIntegerField(choices=[(0, '停止'), (1, '运行')], default=1),
        ),
    ]
