# Generated by Django 2.2.4 on 2019-09-07 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0003_auto_20190907_1445'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='lastday_assets',
        ),
        migrations.CreateModel(
            name='LastdayAssets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=32)),
                ('lastday_assets', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='deal.Account')),
            ],
        ),
    ]
