# Generated by Django 2.2.3 on 2019-09-27 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0003_auto_20190926_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robot',
            name='annual_yield',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='robot',
            name='float_profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19),
        ),
        migrations.AlterField(
            model_name='robot',
            name='protection',
            field=models.SmallIntegerField(choices=[('保护', 1), ('解除保护', 2)], default=2),
        ),
        migrations.AlterField(
            model_name='robot',
            name='realized_profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19),
        ),
        migrations.AlterField(
            model_name='robot',
            name='status',
            field=models.SmallIntegerField(choices=[('运行中', 1), ('已停止', 0)], default=0),
        ),
        migrations.AlterField(
            model_name='robot',
            name='total_money',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19),
        ),
        migrations.AlterField(
            model_name='robot',
            name='total_profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19),
        ),
    ]
