# Generated by Django 2.2.3 on 2019-10-14 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0003_auto_20191011_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='order_id',
            field=models.SmallIntegerField(max_length=32),
        ),
    ]
