# Generated by Django 2.2.3 on 2019-10-14 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0004_auto_20191014_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='order_id',
            field=models.IntegerField(),
        ),
    ]
