# Generated by Django 2.2.3 on 2019-09-27 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0004_auto_20190927_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robot',
            name='annual_yield',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='robot',
            name='float_profit',
            field=models.DecimalField(decimal_places=2, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='robot',
            name='protection',
            field=models.SmallIntegerField(choices=[(1, '保护'), (2, '解除保护')], default=2),
        ),
        migrations.AlterField(
            model_name='robot',
            name='realized_profit',
            field=models.DecimalField(decimal_places=2, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='robot',
            name='status',
            field=models.SmallIntegerField(choices=[(1, '运行中'), (0, '已停止')], default=0),
        ),
        migrations.AlterField(
            model_name='robot',
            name='total_money',
            field=models.DecimalField(decimal_places=2, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='robot',
            name='total_profit',
            field=models.DecimalField(decimal_places=2, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='robot',
            name='warning_account',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
