# Generated by Django 2.2.3 on 2019-09-09 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0004_auto_20190907_1456'),
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Robot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=32)),
                ('market', models.CharField(max_length=32)),
                ('trading_strategy', models.CharField(max_length=32)),
                ('total_money', models.DecimalField(decimal_places=2, max_digits=19)),
                ('float_profit', models.DecimalField(decimal_places=2, max_digits=19)),
                ('realized_profit', models.DecimalField(decimal_places=2, max_digits=19)),
                ('total_profit', models.DecimalField(decimal_places=2, max_digits=19)),
                ('annual_yield', models.DecimalField(decimal_places=2, max_digits=5)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.SmallIntegerField(choices=[('运行中', 1), ('已停止', 0)])),
                ('trading_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deal.Account')),
            ],
            options={
                'ordering': ['-create_time'],
            },
        ),
    ]
