# Generated by Django 2.2.3 on 2019-09-27 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0005_auto_20190927_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robot',
            name='warning_account',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
