# Generated by Django 2.2.3 on 2019-09-29 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0006_auto_20190927_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robot',
            name='protection',
            field=models.SmallIntegerField(choices=[(1, '保护'), (0, '解除保护')], default=2),
        ),
        migrations.AlterField(
            model_name='robot',
            name='status',
            field=models.SmallIntegerField(choices=[(1, '运行中'), (0, '已停止'), (2, '保护'), (3, '解除保护')], default=0),
        ),
    ]
