# Generated by Django 2.2.3 on 2019-10-16 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0006_auto_20191014_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='robot',
            name='running_time',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
