# Generated by Django 2.2.3 on 2019-10-17 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0007_robot_running_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='robot',
            name='warning_time',
            field=models.CharField(default=0, max_length=32),
            preserve_default=False,
        ),
    ]
