# Generated by Django 2.2.3 on 2019-09-30 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0007_auto_20190930_0958'),
        ('deal', '0007_auto_20190929_1928'),
    ]

    operations = [
    ]
