# Generated by Django 2.2.3 on 2019-10-17 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0008_robot_warning_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robot',
            name='total_money',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
