# Generated by Django 2.2.3 on 2019-09-30 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0009_auto_20190930_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robot',
            name='run_status',
            field=models.SmallIntegerField(choices=[(0, '停止'), (1, '运行')], default=0),
        ),
    ]
