# Generated by Django 2.2.4 on 2019-08-23 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0003_auto_20190823_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='status',
            field=models.CharField(choices=[('1', '正常'), ('0', '禁用')], default='1', max_length=10),
        ),
    ]
