# Generated by Django 2.2.4 on 2019-08-19 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={},
        ),
        migrations.AlterModelOptions(
            name='permission',
            options={},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={},
        ),
        migrations.AlterModelOptions(
            name='userinfo',
            options={},
        ),
        migrations.AlterField(
            model_name='menu',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rbac.Menu'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='title',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='permission',
            name='menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rbac.Menu'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='title',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='permission',
            name='url',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(to='rbac.Permission'),
        ),
        migrations.AlterField(
            model_name='role',
            name='title',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='nickname',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='password',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='roles',
            field=models.ManyToManyField(to='rbac.Role'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='username',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterModelTable(
            name='menu',
            table=None,
        ),
        migrations.AlterModelTable(
            name='permission',
            table=None,
        ),
        migrations.AlterModelTable(
            name='role',
            table=None,
        ),
        migrations.AlterModelTable(
            name='userinfo',
            table=None,
        ),
    ]
