# Generated by Django 2.2.3 on 2019-10-22 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(to='rbac.Permission'),
        ),
    ]
