# Generated by Django 2.2.4 on 2019-08-17 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='roles',
            new_name='role',
        ),
    ]
