# Generated by Django 2.2.3 on 2019-09-05 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='permissions',
            new_name='permission',
        ),
    ]
