# Generated by Django 2.2.4 on 2019-09-05 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userinfo',
            options={'ordering': ['-create_time']},
        ),
    ]
