# Generated by Django 2.2.4 on 2019-09-09 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0002_auto_20190905_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='type',
            field=models.SmallIntegerField(default=0, max_length=10),
        ),
    ]
