# Generated by Django 2.2.3 on 2019-08-22 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0002_auto_20190817_1502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='permission',
        ),
        migrations.AddField(
            model_name='role',
            name='permission',
            field=models.ManyToManyField(to='rbac.Permission'),
        ),
    ]
