# Generated by Django 2.2.4 on 2019-09-10 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0003_userinfo_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='type',
            field=models.SmallIntegerField(default=0),
        ),
    ]
