# Generated by Django 2.2.3 on 2019-09-30 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0004_auto_20190910_1037'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='permissions',
            new_name='permission',
        ),
    ]
