# Generated by Django 2.2.4 on 2019-08-28 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0004_auto_20190823_1603'),
    ]

    operations = [

        migrations.RenameField(
            model_name='role',
            old_name='title',
            new_name='rolename',
        ),
    ]
