# Generated by Django 2.2.4 on 2019-08-28 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0005_auto_20190828_1051'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='rolename',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='status',
            field=models.CharField(max_length=10),
        ),
    ]
